from typing import List, Dict, Any, Optional, AsyncGenerator
import time
import logging
import asyncio
from collections import deque

logger = logging.getLogger(__name__)


class InferenceEngine:
    """Simulated inference engine for demonstration purposes.

    In production, this would interface with vLLM, TGI, or similar.
    """

    def __init__(self, model_name: str, device: str = "cpu"):
        self.model_name = model_name
        self.device = device
        self._loaded = False
        self._start_time = time.time()
        logger.info(f"InferenceEngine initialized: {model_name} on {device}")

    async def load_model(self):
        """Load the model into memory."""
        logger.info(f"Loading model: {self.model_name}")
        # Simulate model loading
        await asyncio.sleep(0.1)
        self._loaded = True
        logger.info(f"Model loaded: {self.model_name}")

    async def unload_model(self):
        """Unload the model from memory."""
        self._loaded = False
        logger.info(f"Model unloaded: {self.model_name}")

    def is_loaded(self) -> bool:
        return self._loaded

    async def generate(
        self,
        prompt: str,
        max_tokens: int = 512,
        temperature: float = 0.7,
    ) -> Dict[str, Any]:
        """Generate text from a prompt."""
        if not self._loaded:
            await self.load_model()

        start_time = time.time()

        # Simulate inference latency
        # In reality, this would call the actual model
        simulated_tokens = max_tokens // 4  # Simulate fewer tokens
        await asyncio.sleep(0.05 + (simulated_tokens * 0.001))

        # Generate simulated output
        generated_text = self._simulate_generation(prompt, simulated_tokens)

        latency_ms = (time.time() - start_time) * 1000

        return {
            "generated_text": generated_text,
            "tokens_generated": simulated_tokens,
            "latency_ms": round(latency_ms, 2),
            "model_used": self.model_name,
        }

    async def generate_stream(
        self,
        prompt: str,
        max_tokens: int = 512,
        temperature: float = 0.7,
    ) -> AsyncGenerator[str, None]:
        """Stream generated text token by token."""
        if not self._loaded:
            await self.load_model()

        simulated_tokens = max_tokens // 4
        words = self._simulate_generation(prompt, simulated_tokens).split()

        for word in words:
            await asyncio.sleep(0.02)
            yield word + " "

    async def batch_generate(
        self,
        prompts: List[str],
        max_tokens: int = 512,
        temperature: float = 0.7,
    ) -> List[Dict[str, Any]]:
        """Generate text for multiple prompts (batched)."""
        results = []

        # Simulate batch processing (more efficient than individual)
        batch_start = time.time()
        await asyncio.sleep(0.1 + (len(prompts) * 0.02))

        for prompt in prompts:
            simulated_tokens = max_tokens // 4
            generated_text = self._simulate_generation(prompt, simulated_tokens)

            results.append({
                "generated_text": generated_text,
                "tokens_generated": simulated_tokens,
                "latency_ms": 0,  # Will be calculated per-item
                "model_used": self.model_name,
                "batch_size": len(prompts),
            })

        # Calculate per-item latency
        batch_latency = (time.time() - batch_start) * 1000
        for result in results:
            result["latency_ms"] = round(batch_latency / len(prompts), 2)

        return results

    def _simulate_generation(self, prompt: str, num_tokens: int) -> str:
        """Simulate text generation."""
        # Simple simulation - in reality, this would use the actual model
        templates = [
            "Based on the provided context, here is the analysis: {topic}. "
            "The key points to consider are relevance, accuracy, and completeness.",
            "This is a simulated response for demonstration purposes. "
            "In production, this would be generated by an actual language model.",
            "The answer to your question involves several factors. "
            "First, consider the context. Second, evaluate the requirements.",
        ]

        import random
        base_text = random.choice(templates)
        topic = prompt[:50] if prompt else "the given input"
        return base_text.format(topic=topic)

    def get_info(self) -> Dict[str, Any]:
        """Return model information."""
        return {
            "model_name": self.model_name,
            "device": self.device,
            "loaded": self._loaded,
            "uptime_seconds": round(time.time() - self._start_time, 2),
        }


class BatchScheduler:
    """Dynamic batching scheduler for optimizing GPU utilization."""

    def __init__(self, max_batch_size: int = 16, timeout_ms: int = 100):
        self.max_batch_size = max_batch_size
        self.timeout_ms = timeout_ms
        self.pending_requests = deque()
        self.batch_count = 0
        self.total_items_batched = 0

    async def add_request(self, request_data: Dict[str, Any]) -> Any:
        """Add a request to the batch scheduler."""
        future = asyncio.Future()
        self.pending_requests.append((request_data, future))

        # Check if we should form a batch
        if len(self.pending_requests) >= self.max_batch_size:
            await self._process_batch()
        else:
            # Wait for more requests or timeout
            try:
                await asyncio.wait_for(
                    asyncio.sleep(self.timeout_ms / 1000),
                    timeout=self.timeout_ms / 1000
                )
                if self.pending_requests:
                    await self._process_batch()
            except asyncio.TimeoutError:
                if self.pending_requests:
                    await self._process_batch()

        return await future

    async def _process_batch(self):
        """Process the current batch of requests."""
        if not self.pending_requests:
            return

        batch = []
        while self.pending_requests and len(batch) < self.max_batch_size:
            request_data, future = self.pending_requests.popleft()
            batch.append((request_data, future))

        self.batch_count += 1
        self.total_items_batched += len(batch)

        logger.info(f"Processing batch {self.batch_count} with {len(batch)} items")

        # In reality, this would call the inference engine with the batch
        # For now, we just resolve the futures
        for request_data, future in batch:
            if not future.done():
                future.set_result({"batch_id": self.batch_count, "status": "processed"})

    def get_stats(self) -> Dict[str, Any]:
        """Return batching statistics."""
        return {
            "batch_count": self.batch_count,
            "total_items_batched": self.total_items_batched,
            "avg_batch_size": (
                self.total_items_batched / self.batch_count
                if self.batch_count > 0
                else 0
            ),
            "pending_requests": len(self.pending_requests),
        }
