apiVersion: v1
kind: Service
metadata:
  name: inference-server
  namespace: ai-inference
  labels:
    app: inference-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8003
      protocol: TCP
      name: http
  selector:
    app: inference-server
